name: schematic_diagrams
description: "Modular, reactive, and interactive schematic diagrams package"
version: 0.0.1
homepage: https://github.com/alettsy/schematic_diagrams
repository: https://github.com/alettsy/schematic_diagrams
issue_tracker: https://github.com/alettsy/schematic_diagrams/issues
funding:
  - https://ko-fi.com/W7C027ZZTS

environment:
  sdk: ^3.11.4
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

platforms:
  windows:
  linux:
  macos:
  android:
  ios:
  web:

topics:
  - flutter
  - schematics
  - diagrams
  - pid
  - visualization
