name: ci
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install justfile
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run full checks
        run: just bc
